--DROP TABLE CUSTOMER_ENTITY IF EXISTS;
CREATE TABLE IF NOT EXISTS CUSTOMER_ENTITY (
    id UUID DEFAULT RANDOM_UUID() NOT NULL,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT NULL,
    LAST_MODIFIED_ON TIMESTAMP DEFAULT NULL
);