DROP TABLE CUSTOMER_ENTITY IF EXISTS;
CREATE TABLE IF NOT EXISTS CUSTOMER_ENTITY (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT NULL,
    LAST_MODIFIED_ON TIMESTAMP DEFAULT NULL
);

DROP TABLE PAYMENT_METHOD_ENTITY IF EXISTS;
CREATE TABLE IF NOT EXISTS PAYMENT_METHOD_ENTITY (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT NULL,
    LAST_MODIFIED_ON TIMESTAMP DEFAULT NULL
);